/// Guest handler — /guest/* endpoints (QR portal + AI chat)
library;

import 'dart:convert';
import 'dart:math';
import 'package:shelf/shelf.dart';
import 'package:shelf_router/shelf_router.dart';
import 'package:dart_jsonwebtoken/dart_jsonwebtoken.dart';
import '../firebase_service.dart';
import '../gemini_service.dart';
import '../gemma_service.dart';
import '../escalation_service.dart';
import '../websocket_service.dart';
import '../config.dart';

final _rng = Random.secure();
final _activeSessions = <String, Map<String, dynamic>>{};
final _rateLimits = <String, List<int>>{};
final _blacklist = <String>{};
final _abuseScores = <String, int>{};

const _sessionTtlMs = 15 * 60 * 1000;

final _spamPatterns = [
  RegExp(r'^(test|hello|hi|hey|lol|haha|asdf|qwerty|[a-z]{1,2})$',
      caseSensitive: false),
  RegExp(r'(.)\1{4,}'),
];

Response _json(int status, dynamic body) => Response(
      status,
      body: jsonEncode(body),
      headers: {'Content-Type': 'application/json'},
    );

Future<Map<String, dynamic>> _parseBody(Request req) async {
  final body = await req.readAsString();
  return body.isEmpty ? {} : jsonDecode(body) as Map<String, dynamic>;
}

String _randHex(int bytes) {
  final buf = List<int>.generate(bytes, (_) => _rng.nextInt(256));
  return buf.map((b) => b.toRadixString(16).padLeft(2, '0')).join();
}

/// Haversine distance between two GPS coordinates in metres
double _haversineMeters(
    double lat1, double lng1, double lat2, double lng2) {
  const r = 6371000.0; // Earth radius in metres
  final dLat = (lat2 - lat1) * (pi / 180);
  final dLng = (lng2 - lng1) * (pi / 180);
  final a = sin(dLat / 2) * sin(dLat / 2) +
      cos(lat1 * pi / 180) *
          cos(lat2 * pi / 180) *
          sin(dLng / 2) *
          sin(dLng / 2);
  return r * 2 * atan2(sqrt(a), sqrt(1 - a));
}

String _signQr(Map<String, dynamic> payload, String secret) {
  final jwt = JWT(payload, issuer: 'crisisync');
  return jwt.sign(SecretKey(secret),
      expiresIn: const Duration(minutes: 15));
}

String _signSession(Map<String, dynamic> payload) {
  final secret = env('JWT_SECRET', 'crisis-responder-secret');
  final jwt = JWT(payload);
  return jwt.sign(SecretKey(secret),
      expiresIn: const Duration(minutes: 15));
}

Map<String, dynamic>? _verifySession(String token) {
  try {
    final secret = env('JWT_SECRET', 'crisis-responder-secret');
    final jwt = JWT.verify(token, SecretKey(secret));
    return jwt.payload as Map<String, dynamic>;
  } catch (_) {
    return null;
  }
}

Map<String, dynamic>? _verifyQr(String token, String secret) {
  try {
    final jwt = JWT.verify(token, SecretKey(secret),
        issuer: 'crisisync');
    return jwt.payload as Map<String, dynamic>;
  } catch (_) {
    return null;
  }
}

Router buildGuestRouter() {
  final router = Router();
  final qrSecret =
      env('QR_PROPERTY_SECRET', 'grand-thalassa-property-2025');

  // GET /guest/scan/:zoneId  ← permanent QR URL
  router.get('/scan/<zoneId>', (Request req, String zoneId) async {
    final zoneName = Uri.decodeComponent(
        req.url.queryParameters['zone'] ?? zoneId);

    final payload = {
      'zoneId': zoneId,
      'zoneName': zoneName,
      'propertyId': 'grand-thalassa-hotel',
      'issuedAt': DateTime.now().millisecondsSinceEpoch,
      'nonce': _randHex(8),
    };

    final qrToken = _signQr(payload, qrSecret);

    // The guest app is served on port 5000 (Flutter web)
    final guestAppUrl = env('GUEST_APP_URL', 'http://localhost:5000');
    return Response.found(
        '$guestAppUrl/?token=$qrToken&zone=${Uri.encodeComponent(zoneName)}');
  });

  // GET /guest/static-qr/:zoneId
  router.get('/static-qr/<zoneId>', (Request req, String zoneId) async {
    final zoneName = Uri.decodeComponent(
        req.url.queryParameters['zone'] ?? zoneId);
    final backendUrl = env('BACKEND_URL', 'http://localhost:8080');
    final permanentUrl =
        '$backendUrl/guest/scan/$zoneId?zone=${Uri.encodeComponent(zoneName)}';
    return _json(200, {
      'info':
          'Embed this URL in your physical QR code. It never expires. Each scan creates a fresh 15-minute guest session.',
      'permanentUrl': permanentUrl,
      'zone': {'id': zoneId, 'name': zoneName},
    });
  });

  // POST /guest/generate-qr
  router.post('/generate-qr', (Request req) async {
    final body = await _parseBody(req);
    final zoneId = body['zoneId'] as String? ?? '';
    final zoneName = body['zoneName'] as String? ?? '';
    final propertyKey = body['propertyKey'] as String? ?? '';

    if (propertyKey != qrSecret) {
      return _json(403, {
        'error': 'INVALID_PROPERTY',
        'message':
            'This QR code was not generated by a registered property.',
      });
    }
    if (zoneId.isEmpty || zoneName.isEmpty) {
      return _json(400, {'error': 'zoneId and zoneName are required'});
    }

    final payload = {
      'zoneId': zoneId,
      'zoneName': zoneName,
      'propertyId': 'grand-thalassa-hotel',
      'issuedAt': DateTime.now().millisecondsSinceEpoch,
      'nonce': _randHex(8),
    };
    final qrToken = _signQr(payload, qrSecret);
    final backendUrl = env('BACKEND_URL', 'http://localhost:8080');
    final guestUrl = '$backendUrl/guest/scan/$zoneId?zone=${Uri.encodeComponent(zoneName)}';

    return _json(200, {
      'success': true,
      'qrToken': qrToken,
      'guestUrl': guestUrl,
      'expiresIn': '15 minutes',
      'zone': {'id': zoneId, 'name': zoneName},
    });
  });

  // POST /guest/verify-token  (Flutter guest app calls this to validate QR token)
  // Body: { token, lat?, lng? }
  // - lat/lng absent → LOCATION_REQUIRED (403)
  // - lat/lng present but outside hotel → OUTSIDE_PROPERTY (403)
  // - inside hotel → 200 with sessionToken
  router.post('/verify-token', (Request req) async {
    final body = await _parseBody(req);
    final token = body['token'] as String? ?? '';
    if (token.isEmpty) {
      return _json(400, {'error': 'token is required'});
    }

    // ── Step 1: Verify JWT ────────────────────────────────────────
    final payload = _verifyQr(token, qrSecret);
    if (payload == null) {
      return _json(401, {'error': 'TOKEN_EXPIRED_OR_INVALID'});
    }

    final nonce = payload['nonce'] as String? ?? '';
    final sessionKey = 'session_$nonce';

    if (_activeSessions[sessionKey]?['used'] == true) {
      return _json(409, {
        'error': 'SESSION_ALREADY_USED',
        'message': 'This QR token is already in use. Please re-scan a fresh QR code.',
      });
    }

    // ── Step 2: Hard GPS location gate ───────────────────────────
    final lat = body['lat'];
    final lng = body['lng'];

    if (lat == null || lng == null) {
      return _json(403, {
        'error': 'LOCATION_REQUIRED',
        'message':
            'Location access is required to use the CrisisSync guest portal. '
            'Please enable GPS and re-scan the QR code.',
      });
    }

    // Hotel coordinates (configurable via .env)
    final hotelLat =
        double.tryParse(env('HOTEL_LAT', '12.9716')) ?? 12.9716;
    final hotelLng =
        double.tryParse(env('HOTEL_LNG', '77.5946')) ?? 77.5946;
    final maxMeters =
        double.tryParse(env('HOTEL_RADIUS_M', '300')) ?? 300.0;

    final guestLat = double.tryParse(lat.toString());
    final guestLng = double.tryParse(lng.toString());

    if (guestLat == null || guestLng == null) {
      return _json(400, {'error': 'Invalid lat/lng values'});
    }

    final distance = _haversineMeters(hotelLat, hotelLng, guestLat, guestLng);

    if (distance > maxMeters) {
      return _json(403, {
        'error': 'OUTSIDE_PROPERTY',
        'message':
            'You appear to be ${distance.round()}m from the hotel. '
            'This QR portal is only accessible from within the property. '
            'Please ensure you are inside the hotel and try again.',
        'distanceMeters': distance.round(),
        'allowedRadius': maxMeters.round(),
      });
    }

    // ── Step 3: Create session ────────────────────────────────────
    final now = DateTime.now().millisecondsSinceEpoch;
    _activeSessions[sessionKey] = {
      'zoneId': payload['zoneId'],
      'zoneName': payload['zoneName'],
      'issuedAt': payload['issuedAt'],
      'used': true,
    };

    // Clean expired sessions
    _activeSessions.removeWhere(
        (_, v) => now - (v['issuedAt'] as int) > _sessionTtlMs * 2);

    final sessionToken = _signSession({
      'zoneId': payload['zoneId'],
      'zoneName': payload['zoneName'],
      'nonce': nonce,
    });

    return _json(200, {
      'sessionToken': sessionToken,
      'zoneId': payload['zoneId'],
      'zoneName': payload['zoneName'],
      'locationStatus': 'verified',
      'locationVerified': true,
      'distanceMeters': distance.round(),
    });
  });


  // POST /guest/verify-location
  router.post('/verify-location', (Request req) async {
    final body = await _parseBody(req);
    final sessionToken = body['sessionToken'] as String? ?? '';
    final lat = body['lat'];
    final lng = body['lng'];

    if (sessionToken.isEmpty) {
      return _json(400, {'error': 'Missing sessionToken'});
    }
    if (_verifySession(sessionToken) == null) {
      return _json(401, {'error': 'Invalid or expired session'});
    }

    if (lat == null || lng == null) {
      return _json(200, {
        'verified': false,
        'reason': 'LOCATION_DENIED',
        'message':
            'Location not shared. Session continues with reduced trust level.',
      });
    }

    final hotelLat =
        double.tryParse(env('HOTEL_LAT', '12.9716')) ?? 12.9716;
    final hotelLng =
        double.tryParse(env('HOTEL_LNG', '77.5946')) ?? 77.5946;
    final maxMeters =
        double.tryParse(env('HOTEL_RADIUS_M', '300')) ?? 300.0;

    final guestLat = double.tryParse(lat.toString());
    final guestLng = double.tryParse(lng.toString());

    if (guestLat == null || guestLng == null) {
      return _json(400, {'error': 'Invalid lat/lng values'});
    }

    final distance =
        _haversineMeters(hotelLat, hotelLng, guestLat, guestLng);

    if (distance <= maxMeters) {
      return _json(200, {
        'verified': true,
        'distance': distance.round(),
        'message':
            '✅ Location verified — you are ${distance.round()}m from hotel center.',
      });
    } else {
      _abuseScores[sessionToken] =
          (_abuseScores[sessionToken] ?? 0) + 2;
      return _json(200, {
        'verified': false,
        'distance': distance.round(),
        'reason': 'OUTSIDE_PROPERTY',
        'message':
            '⚠️ You appear to be ${distance.round()}m away. This QR is for in-property guests only.',
      });
    }
  });

  // POST /guest/message
  router.post('/message', (Request req) async {
    final body = await _parseBody(req);
    final sessionToken = body['sessionToken'] as String? ?? '';
    final message = body['message'] as String? ?? '';

    if (sessionToken.isEmpty || message.isEmpty) {
      return _json(400,
          {'error': 'sessionToken and message are required'});
    }

    final sessionData = _verifySession(sessionToken);
    if (sessionData == null) {
      return _json(401, {
        'error': 'SESSION_EXPIRED',
        'message': 'Your session has expired. Please re-scan the QR code.',
      });
    }

    if (_blacklist.contains(sessionToken)) {
      return _json(403, {
        'error': 'SESSION_BLOCKED',
        'message':
            'This session has been blocked due to suspicious activity.',
      });
    }

    // Rate limit: 5 messages per 10 minutes
    final now = DateTime.now().millisecondsSinceEpoch;
    final times = _rateLimits[sessionToken] ?? [];
    final recent =
        times.where((t) => now - t < 10 * 60 * 1000).toList();
    if (recent.length >= 5) {
      return _json(429, {
        'error': 'RATE_LIMITED',
        'message':
            'Too many messages. Please wait a moment or find a nearby staff member.',
      });
    }
    recent.add(now);
    _rateLimits[sessionToken] = recent;

    // Spam check
    final isSpam =
        _spamPatterns.any((p) => p.hasMatch(message.trim()));
    if (isSpam) {
      _abuseScores[sessionToken] =
          (_abuseScores[sessionToken] ?? 0) + 1;
      if ((_abuseScores[sessionToken] ?? 0) >= 3) {
        _blacklist.add(sessionToken);
        return _json(403, {
          'error': 'SESSION_BLOCKED',
          'message':
              'This session has been blocked due to repeated suspicious activity.',
        });
      }
      return _json(200, {
        'aiReply':
            "I'm here to help with genuine questions or emergencies. Please describe your concern clearly.",
        'classification': 'info',
        'incidentCreated': false,
      });
    }

    final zoneId = sessionData['zoneId'] as String;
    final zoneName = sessionData['zoneName'] as String;

    try {
      final classification =
          await classifyIncident(message, zoneName);
      final severity = classification['severity'] as String;

      String aiReply;
      bool incidentCreated = false;
      String incidentId = '';

      if (severity == 'critical') {
        incidentId = 'INC-${DateTime.now().millisecondsSinceEpoch}';
        // RAG-enhanced protocol: first try Gemma 4, fall back to Gemini
        final ragProtocol = await generateCrisisProtocol(message, zoneName);
        final actionPlan = ragProtocol.isNotEmpty
            ? ragProtocol.split('\n').where((l) => l.trim().isNotEmpty).take(5).toList()
            : await generateEmergencyProtocol(
                classification['category'] as String, zoneName, message);


        final incidentData = {
          'id': incidentId,
          'title':
              '${(classification['category'] as String).toUpperCase()} — Guest Alert ($zoneName)',
          'description': message,
          'zoneId': zoneId,
          'severity': 'critical',
          'status': 'pending',
          'createdBy': 'guest_portal',
          'standbyResponders': [],
          'createdAt': now,
          'aiConfidence':
              (classification['confidence'] as num).toDouble() / 100,
          'aiClassification': classification['category'],
        };
        await dbSet('incidents/$incidentId', incidentData);

        broadcast('hardware_alert', {
          'title':
              '🚨 Guest Emergency: ${(classification['category'] as String).toUpperCase()}',
          'zone': zoneName,
          'description': message,
          'actionPlan': actionPlan,
        });

        await escalateIncident(
          incidentId: incidentId,
          type: classification['category'] as String,
          zone: zoneName,
          zoneId: zoneId,
          description: message,
          confidence:
              (classification['confidence'] as num).toDouble() / 100,
          actionPlan: actionPlan,
          source: 'guest_qr',
        );

        aiReply =
            '🚨 Emergency services have been alerted. Help is on the way to $zoneName. Please remain calm. ${classification['suggestedAction']}';
        incidentCreated = true;
      } else if (severity == 'warning') {
        final aiResponse = await answerGuestQuestion(message);
        aiReply =
            '${aiResponse['answer']} Our team has been notified and will assist you shortly.';
        incidentId =
            'INC-${DateTime.now().millisecondsSinceEpoch}';
        await dbSet('incidents/$incidentId', {
          'id': incidentId,
          'title': 'Service Request — $zoneName',
          'description': message,
          'zoneId': zoneId,
          'severity': 'warning',
          'status': 'pending',
          'createdBy': 'guest_portal',
          'standbyResponders': [],
          'createdAt': now,
          'aiConfidence':
              (classification['confidence'] as num).toDouble() / 100,
          'aiClassification': classification['category'],
        });
        incidentCreated = true;
      } else {
        final aiResponse = await answerGuestQuestion(message);
        aiReply = aiResponse['answer'] as String;
      }

      return _json(200, {
        'aiReply': aiReply,
        'classification': severity,
        'incidentCreated': incidentCreated,
        'incidentId': incidentId.isNotEmpty ? incidentId : null,
        'zoneName': zoneName,
      });
    } catch (e) {
      print('[guest/message] $e');
      return _json(500, {
        'error':
            'Failed to process your message. Please find a staff member nearby.'
      });
    }
  });

  return router;
}
